Fix reviewdog failure handling in GrumPHP workflow by using echo for environment variable assignment

diff --git a/.github/workflows/grumphp_standards_checker.yaml b/.github/workflows/grumphp_standards_checker.yaml
--- a/.github/workflows/grumphp_standards_checker.yaml
+++ b/.github/workflows/grumphp_standards_checker.yaml
@@ -65,7 +65,7 @@ jobs:
           if [ -s "$STDERR_FILE" ]; then
           cat "$STDERR_FILE" \
             | sed -r "s/([0-9]+)\s+/\1:/gI" \
-            | reviewdog -fail-level=any -f=phpstan -name="PHPMD GrumPHP"  -reporter=github-pr-review -filter-mode=nofilter || REVIEWDOG_FAILED=1 >> $GITHUB_ENV
+            | reviewdog -fail-level=any -f=phpstan -name="PHPMD GrumPHP"  -reporter=github-pr-review -filter-mode=nofilter || echo REVIEWDOG_FAILED=1 >> $GITHUB_ENV
           else
             echo "No errors found in PHP files. Skipping reviewdog."
           fi
@@ -87,7 +87,7 @@ jobs:
           # Check if STDERR_FILE is non-empty
           if [ -s "$STDERR_FILE" ]; then
             # Pass stderr to reviewdog
-            cat "$STDERR_FILE" | reviewdog -fail-level=any -f=checkstyle -name="PHPCS GrumPHP" -reporter=github-pr-review -filter-mode=nofilter || REVIEWDOG_FAILED=1 >> $GITHUB_ENV
+            cat "$STDERR_FILE" | reviewdog -fail-level=any -f=checkstyle -name="PHPCS GrumPHP" -reporter=github-pr-review -filter-mode=nofilter || echo REVIEWDOG_FAILED=1 >> $GITHUB_ENV
           else
             echo "No errors found in PHP files. Skipping reviewdog."
           fi
@@ -109,7 +109,7 @@ jobs:
           # Check if STDERR_FILE is non-empty
           if [ -s "$STDERR_FILE" ]; then
             # Pass stderr to reviewdog
-            cat "$STDERR_FILE" | reviewdog -fail-level=any -f=eslint -name="Eslint GrumPHP" -reporter=github-pr-review -filter-mode=nofilter || REVIEWDOG_FAILED=1 >> $GITHUB_ENV
+            cat "$STDERR_FILE" | reviewdog -fail-level=any -f=eslint -name="Eslint GrumPHP" -reporter=github-pr-review -filter-mode=nofilter || echo REVIEWDOG_FAILED=1 >> $GITHUB_ENV
           else
             echo "No errors found in JS files. Skipping reviewdog."
           fi
